// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe7TKAVmHcZEz-2bZtz9n6RQZZofqSync',
    appId: '1:728452526715:web:c2a8cd7a0e3ad640aea8de',
    messagingSenderId: '728452526715',
    projectId: 'yatra-60edb',
    authDomain: 'yatra-60edb.firebaseapp.com',
    storageBucket: 'yatra-60edb.appspot.com',
    measurementId: 'G-DKGEK9PD4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQllEOEcBCa3-DE7YdwEmSx3VShSwNf3s',
    appId: '1:728452526715:android:09b9e6a2439bdf7baea8de',
    messagingSenderId: '728452526715',
    projectId: 'yatra-60edb',
    storageBucket: 'yatra-60edb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt_L8KVqsy-FSwiS63_Y-GVdMr3_PZORs',
    appId: '1:728452526715:ios:33f19a71d12bc60daea8de',
    messagingSenderId: '728452526715',
    projectId: 'yatra-60edb',
    storageBucket: 'yatra-60edb.appspot.com',
    iosBundleId: 'com.example.yatra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt_L8KVqsy-FSwiS63_Y-GVdMr3_PZORs',
    appId: '1:728452526715:ios:33f19a71d12bc60daea8de',
    messagingSenderId: '728452526715',
    projectId: 'yatra-60edb',
    storageBucket: 'yatra-60edb.appspot.com',
    iosBundleId: 'com.example.yatra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDe7TKAVmHcZEz-2bZtz9n6RQZZofqSync',
    appId: '1:728452526715:web:ec2e110cab6411e8aea8de',
    messagingSenderId: '728452526715',
    projectId: 'yatra-60edb',
    authDomain: 'yatra-60edb.firebaseapp.com',
    storageBucket: 'yatra-60edb.appspot.com',
    measurementId: 'G-299102QGTF',
  );
}
